Licencja: "podaj-licencje" # Licencje dostajesz po zakupie u Iknemko (discord.gg/R5xXeTvCm3)
# ---------------------------------------------------------------------
# PRZYDATNE INFORMACJE:
# Plugin wspiera kolory od MiniMessage (https://webui.advntr.dev)
# Plugin wspiera prosty kalkulator Calculate[obliczenie]
# Plugin wspiera zamienianie liter na ma≈Çy caps smallCaps[tekst]
# ---------------------------------------------------------------------
tiktok_name: "twojanazwa" # Podaj nazwƒô z tiktoka.
# ---------------------------------------------------------------------
customGiftImages: true # W≈ÇƒÖcza texturepack serwerowy ze zdjƒôciami gift√≥w
clearStatistics: false # Czy co w≈ÇƒÖczenie serwera ma czy≈õciƒá topki
giftCombo: true # Czy ma na bie≈ºƒÖco wysy≈Çaƒá gifty, czy za jednym razem
async: false # Gdyby wystƒôpowa≈Çy lagi na serwerze zaleca siƒô w≈ÇƒÖczyƒá tƒô funkcjƒô.
# ---------------------------------------------------------------------
shortName:  # Gdy nazwa u≈ºytkownika jest za d≈Çuga zwraca pierwsze 15 znak√≥w
  enable: true # Czy nazwa u≈ºytkownika ma byƒá mniejsza gdy jest za d≈Çuga?
  maxLength: 15 # Jak d≈Çuga mo≈ºe byƒá nazwa u≈ºytkownika
# ---------------------------------------------------------------------
giftHistoryScheme: # {giftHistory_X} - X to liczba ile zwr√≥ciƒá ma ostatnich gift√≥w
  minimumGiftCost: 1 # Minimalna cena gifta, aby go pokaza≈Ço w historii gift√≥w.
  smallText: false
  message: "{giftImage} "
# ---------------------------------------------------------------------
giveawayCommand:
  minimum-role: follower # role: host, admin, mod, subscriber, gifter, follower, default
  join-message: "&#FB9E00&l[Giveaway] {prefix}&f{nickname} &#FDDC00do≈ÇƒÖczy≈Ç do losowania!"
  winner-message: "&#00C200&l[Giveaway] &7Losowanie wygrywa &#60FE60{winner}&7, gratulacje!"
  bossbar:
    color: GREEN
    overlay: "PROGRESS" # NOTCHED_20, NOTCHED_12, NOTCHED_10, NOTCHED_6, PROGRESS
    message: "&8‚Ä¢ &#95FF8ENapisz &f{word} &8:|: &#95FF8EWyniki losowania za &f{time}sek. &8‚Ä¢"
# ---------------------------------------------------------------------
goalCommand:
  bossbar:
    color: GREEN
    refresh: 5 # Czas podawaj w sekundach
    # {message}
    # {time}
    # {giftName}
    # {giftImage}
    # {percentage}
    # {requiredGifts}
    # {currentGifts}
    message: "&3&lCel:&f {giftImage}{giftName} &b({currentGifts}/{requiredGifts}) &8| &f{message}"
# ---------------------------------------------------------------------
bossbar:
  enable: false
  color: WHITE # WHITE BLUE RED GREEN PINK PURPLE YELLOW
  overlay: "NOTCHED_12" # NOTCHED_20, NOTCHED_12, NOTCHED_10, NOTCHED_6, PROGRESS
  displayTime: 10 # Czas podany w sekundach
  messages:
    - '&8x &#B6B6B6Polubie≈Ñ&8: &#81FF7B{totalLikes} &8:|: &#B6B6B6OglƒÖdajƒÖcych&8: &#81FF7B{viewers}
    &8:|: &#B6B6B6Otrzymane monety&8: &#81FF7B{earnedDiamonds} &8x'
    - '&8x <gradient:#2AD4FF:#DF4DFF>Zachƒôcam do zostawienia obserwacji!</gradient> &8x'
# ---------------------------------------------------------------------
alert:
  gift:
    title: "<b><gradient:#FFA046:#FCFFC3>‚ú™ Prezent ‚ú™</gradient></b>" # Aby pokazywa≈Çy siƒô zdjƒôcia ustaw title: "{giftImage}"
# ---------------------------------------------------------------------
requiredLike: 500 # Wymagana ilo≈õƒá polubie≈Ñ, aby siƒô wykona≈Çy komendy.
requiredLike-commands:
  - command -> sudo {streamer} /say Dziƒôki za 500 like!
  - command -> sudo {streamer /alert title-subtitle &eDziƒôki!‚ù§\n<gradient:#50FF46:#27B72B>500 Polubie≈Ñ</gradient>
# ---------------------------------------------------------------------
requiredFollow: 3 # Wymagana ilo≈õƒá follow√≥w, aby siƒô wykona≈Çy komendy.
requiredFollow-commands:
  - command -> sudo {streamer} /say Obserwacje 3/3
# ---------------------------------------------------------------------
# dostƒôpne opcjƒô: broadcast, command, subtitle, actionbar
# ---------------------------------------------------------------------
# {nickname} - zwraca unikalny nick z tiktoka.
# {displayname} - zwraca wy≈õwietlanƒÖ nazwƒô z tiktoka.
# {prefix} - zwraca rolƒô, jakƒÖ posiada na streamie.
# {giftName} - zwraca nazwƒô wys≈Çanego prezentu.
# {giftImage} - zwraca zdjƒôcie wys≈Çanego prezentu (opcja "customGiftImages" musi byƒá w≈ÇƒÖczona)
# {giftCost} - zwraca, ile kosztowa≈Ço wys≈Çanie giftu/√≥w.
# {giftStreak} - zwraca, ile wys≈Çano z rzƒôdu gift√≥w.
# {gifterLevel} - zwraca poziom badge w dawaniu gift√≥w.
# {profileUrl} - zwraca link do zdjƒôcia profilu u≈ºytkownika.
# {giftUrl} - zwraca link do zdjƒôcia giftu.
gift:
  commands:
    - broadcast -> &#FFDF4D&lPrezent &8| {giftBadge}{fanBadge} &#ADADAD{nickname} &8- &#E8FF00{giftName} &#FFC900x{giftStreak}
# ---------------------------------------------------------------------
# {displayname} - zwraca unikalny nick z tiktoka.
# {displayname} - zwraca wy≈õwietlanƒÖ nazwƒô z tiktoka.
# {prefix} - zwraca rolƒô, jakƒÖ posiada na streamie.
# {giftName} - zwraca nazwƒô wys≈Çanego prezentu.
# {giftImage} - zwraca zdjƒôcie wys≈Çanego prezentu (opcja "customGiftImages" musi byƒá w≈ÇƒÖczona)
# {giftCost} - zwraca, ile kosztowa≈Ço wys≈Çanie giftu/√≥w.
# {giftStreak} - zwraca, ile wys≈Çano z rzƒôdu gift√≥w.
combo:
  commands:
    - command -> alert title-subtitle <b><gradient:#5F9EFF:#BBFFFC>‚ú™ Prezent ‚ú™</gradient></b>\n&a{displayname} &8- {giftImage} &#BBFFFC{giftName} &7(x{giftStreak})
# ---------------------------------------------------------------------
# {nickname} - zwraca unikalny nick z tiktoka.
# {displayname} - zwraca wy≈õwietlanƒÖ nazwƒô z tiktoka.
# {prefix} - zwraca rolƒô, jakƒÖ posiada na streamie.
# {message} - zwraca wiadomo≈õƒá, jakƒÖ napisa≈Ça osoba na czacie transmisji.
# {gifterLevel} - zwraca poziom badge w dawaniu gift√≥w.
# {profileUrl} - zwraca link do zdjƒôcia profilu u≈ºytkownika.
chat:
  commands:
    - broadcast -> &#76FF5E&lCzat &8| {prefix}{giftBadge}{fanBadge} &#ADADAD{displayname} &8¬ª &#ABFF9C{message}
# ---------------------------------------------------------------------
# {nickname} - zwraca unikalny nick z tiktoka.
# {displayname} - zwraca wy≈õwietlanƒÖ nazwƒô z tiktoka.
# {prefix} - zwraca rolƒô, jakƒÖ posiada na streamie.
# {likeCount} - zwraca, ile wys≈Ça≈Ça osoba w danym momencie tapniƒôƒá.
# {likes} - zwraca, ile jest aktualnie polubie≈Ñ do nastƒôpnej nagrody.
# {requiredLike} - zwraca, ile potrzeba polubie≈Ñ do nagrody.
# {gifterLevel} - zwraca poziom badge w dawaniu gift√≥w.
# {profileUrl} - zwraca link do zdjƒôcia profilu u≈ºytkownika.
like:
  commands:
    - actionbar -> &8‚Ä¢ {giftBadge}{fanBadge} &#ED9CFF{nickname} &8- &#F3BDFFpolubi≈Ç ten strimek! &8[&#ED9CFFx{likeCount}&8] &8[&#F3BDFF{likes}&8/&#ED9CFF{requiredLike}&8] &8‚Ä¢
# ---------------------------------------------------------------------
# {nickname} - zwraca unikalny nick z tiktoka.
# {displayname} - zwraca wy≈õwietlanƒÖ nazwƒô z tiktoka.
# {prefix} - zwraca rolƒô, jakƒÖ posiada na streamie.
# {newFollowers} - zwraca, ile przyby≈Ço nowych obserwacji podczas transmisji.
# {gifterLevel} - zwraca poziom badge w dawaniu gift√≥w.
# {followCount} - zwraca licznik ile zosta≈Ço do wykonania requiredFollow
# {requiredFollow} - zwraca, ile trzeba daƒá follow√≥w, aby wykona≈Ço siƒô requiredFollow
# {profileUrl} - zwraca link do zdjƒôcia profilu u≈ºytkownika.
follow:
  commands:
    - broadcast -> &#FFC85C&lObserwacja &8| {giftBadge}{fanBadge} &#ADADAD{displayname} &8- &#FFDC96Dziƒôkuje Ci za obserwacjƒô! &8(&7x&#FFC85C{newFollowers}&8)
    - command -> sudo {streamer} alert title-subtitle <b><gradient:#46FF5A:#FDE200>Obserwacja</gradient></b>\n&fDziƒôkuje &#46FF5A{displayname}&f!
# ---------------------------------------------------------------------
# {nickname} - zwraca unikalny nick z tiktoka.
# {displayname} - zwraca wy≈õwietlanƒÖ nazwƒô z tiktoka.
# {prefix} - zwraca rolƒô, jakƒÖ posiada na streamie.
# {profileUrl} - zwraca link do zdjƒôcia profilu u≈ºytkownika.
join:
  commands:
    - actionbar -> &8‚Ä¢ {giftBadge}{fanBadge} &#5EFF5C{displayname} &8- &#A2FFA1do≈ÇƒÖczy≈Ç/a na strimek! &8‚Ä¢
# {nickname} - zwraca unikalny nick z tiktoka.
# {displayname} - zwraca wy≈õwietlanƒÖ nazwƒô z tiktoka.
# {prefix} - zwraca rolƒô, jakƒÖ posiada na streamie.
# {gifterLevel} - zwraca poziom badge w dawaniu gift√≥w.
# {profileUrl} - zwraca link do zdjƒôcia profilu u≈ºytkownika.
share:
  commands:
    - broadcast -> &#5EADFF&lUdostƒôpnienie &8| {prefix}{giftBadge}{fanBadge} &#ADADAD{displayname} &8- &#8FC4FFDziƒôki za przes≈Çanie transmisji dalej!
# ---------------------------------------------------------------------
# {nickname} - zwraca unikalny nick z tiktoka.
# {displayname} - zwraca wy≈õwietlanƒÖ nazwƒô z tiktoka.
# {prefix} - zwraca rolƒô, jakƒÖ posiada na streamie.
# {gifterLevel} - zwraca poziom badge w dawaniu gift√≥w.
# {profileUrl} - zwraca link do zdjƒôcia profilu u≈ºytkownika.
subscribe:
  commands:
    - broadcast -> &#FF0000&lSubskrypcja &8| {giftBadge}{fanBadge} &7{displayname} &8- &#FF6060Dziƒôki za kupienie subskrypcji!
# ---------------------------------------------------------------------
# {nickname} - zwraca unikalny nick z tiktoka.
# {displayname} - zwraca wy≈õwietlanƒÖ nazwƒô z tiktoka.
# {prefix} - zwraca rolƒô, jakƒÖ posiada na streamie.
# {totalDiamonds} - zwraca, ile monet jest w skrzyni.
# {totalUsers} - zwraca, ile os√≥b mo≈ºe odebraƒá monety.
# {gifterLevel} - zwraca poziom badge w dawaniu gift√≥w.
# {profileUrl} - zwraca link do zdjƒôcia profilu u≈ºytkownika.
chest:
  commands:
    - broadcast -> &#BEF527&lSkrzynia &8| {giftBadge}{fanBadge} &7{displayname} &8- &#D9FA7DWysy≈Ça skrzynie &#A7D132ü™ô{totalDiamonds} &#D9FA7Dmonet dla &#A7D132{totalUsers} &#D9FA7Dos√≥b!
    - command -> sudo {streamer} alert bossbar+ chest YELLOW 15 {giftBadge}{fanBadge} &7{displayname} &8- &#D9FA7DWys≈Ça skrzynie &#A7D132ü™ô{totalDiamonds} &#D9FA7Dmonet dla &#A7D132{totalUsers} &#D9FA7Dos√≥b!
# ---------------------------------------------------------------------
# {nickname} - zwraca podany nick w tipply.
# {value} - zwraca, ile wp≈Çaci≈Ç.
# {message} - zwraca podanƒÖ wiadomo≈õƒá w tipply.
tipply:
  url: "link" # Podaj sw√≥j widget https://widgets.tipply.pl/TIP_ALERT/{twoje id}
  commands:
    - broadcast -> &8[&#da9109Tipply&8] &7{nickname} &fwp≈Çaci≈Ç &#ffbf49{value}z≈Ç &8>> &a{message}
    - command -> alert title-subtitle &#ffbf49{nickname} &fwp≈Çaci≈Ç &#ffbf49{value}z≈Ç\n&a{message}
    - command -> alert bossbar GREEN 60 &8[&#da9109Tipply&8] &7{nickname} &fwp≈Çaci≈Ç &#ffbf49{value}z≈Ç &8>> &a{message}
  keyword-commands:
    siema:
      aliases: [siemka]
      commands:
        - command -> say {nickname} wys≈Ça≈Ç siema w wiadomo≈õci!
# ---------------------------------------------------------------------
giftActions:
  # Aby dodaƒá wykonywanie komendy dodaj do commands: - command -> sudo {streamer} komenda
  # Je≈ºeli chcesz wykonywaƒá obliczenia u≈ºyj CALCULATE[] przyk≈Çad: CALCULATE[25 * 5]
  # {streamer} przypisuje siƒô po wykonaniu komendy /polacz
  rose:
    commands:
      - command -> alert prezent &8‚Ä¢ &a{displayname} &8- &r{giftImage} &#FCFFC3x{giftStreak} &8‚Ä¢
      - command -> sudo {streamer} /say Dziƒôki za r√≥≈ºyczkƒô!
# ---------------------------------------------------------------------
customCommands:
  cooldown-message: "&8{nickname}&7&o, musi poczekaƒá &8{time} &7&ozanim u≈ºyje komendy&7! &8(&f{command}&8)"
  '!test':
    minimum-role: follower # role: host, admin, mod, subscriber, gifter, follower, default
    cooldown: 5 # czas w sekundach
    commands:
      - command -> sudo {streamer} /say Testowa komenda!
# ---------------------------------------------------------------------
giftNames:
  - Rose -> "R√≥≈ºa"
  - Finger-Heart -> "Serce z palc√≥w"
  - Lollipop -> "Lizak"
  - Doughnut -> "PƒÖczek"
  - Mic -> "Mikrofon"
  - Cap -> "Czapka"
  - Gamepad -> "Kontroler"
  - Mirror -> "Lustro"
  - Little-Crown -> "Ma≈Ça korona"
  - Sunglasses -> "Okulary przeciws≈Çoneczne"
  - Heart -> "Serce"
  - Duck -> "Kaczka"
  - Follow -> "Obserwacje"
  - Like -> "Polubienia"
  - Diamonds -> "Diamenty"
# ---------------------------------------------------------------------
roleNames:
  - Host -> "&#FF0000Streamer "
  - Admin -> "<gradient:#FF5F5F:#FFA8CB>Moderator</gradient><reset> "
  - Mod -> "&#46B921Mod "
  - Subscriber -> "<gradient:#FF46DC:#EED3FF>Subskrybuje</gradient><reset> "
  - Gifter -> "<gradient:#4687FF:#C3FFF8>Prezentodawca</gradient><reset> "
  - Follower -> "<gradient:#FFCD46:#FFF9C3>Obserwuje</gradient><reset> "
  - default -> ""